name: Backend CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure using v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensure using v3
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        run: |
          cd kasir/Backend  # Ensure this path is correct
          yarn install

      - name: Run tests
        run: |
          cd kasir/Backend  # Ensure this path is correct
          yarn test
