name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Backend CI
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Backend
          yarn install

      - name: Run backend tests
        run: |
          cd Backend
          yarn test

  frontend:
    runs-on: ubuntu-latest
    name: Frontend CI
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Frontend
          yarn install

      - name: Build frontend
        run: |
          cd Frontend
          yarn build

      - name: Lint frontend
        run: |
          cd Frontend
          yarn lint

  Deploy-Production:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        env:
          VERCEL_TOKEN: ${{ secrets.CICD_KASIR }}
        run: vercel pull --yes --environment=production --token=${{ secrets.CICD_KASIR }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.CICD_KASIR }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.CICD_KASIR }}
