name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        run: |
          cd ./Frontend  # Ensure this path is correct
          yarn install

      - name: Run tests
        run: |
          cd ./Frontend  # Ensure this path is correct
          yarn test

      - name: Build project
        run: |
          cd ./Frontend  # Ensure this path is correct
          yarn build
